### ISSUE TITLE
Upgrade to newest version of KaTeX

### ISSUE THREAD

**Issue by stubailo** [stubailo/meteor-katex#3]

**Comment by kaushik1979** [comment]
Hi Sashko, any update on this one?

**Comment by kaushik1979** [comment]
Hi Sashko, any update on this one? Can you give me an idea when do you plan to get to this so that I can plan accordingly? Thanks.

**Comment by stubailo** [comment]
Hey, currently I don't have plans to do this. If you can fork the package and make it work, I'll publish it, but I don't have time to work on updating it.

On the bright side, there might be some improvements to Meteor coming soon around build plugins that might make it easier to make this work without a ton of manual work.

**Comment by kaushik1979** [comment]
Hi Sashko,

Meteor improvement will be awesome.

At this point, I need my app to go out so I guess I am up for the manual work.

I have taken the latest code for KaTeX and meteor-katex.

I see you have lots of font files in fonts/ folder. Can you briefly explain to me what I need to do between the KaTeX and meteor-katex projects to update meteor-katex?

Thanks for your help again.

**Comment by kaushik1979** [comment]
If that is time taking, can you point me to the correct resources/urls to learn how to package fonts for meteor-application?

**Comment by stubailo** [comment]
I think what you would have to update in this package are the font files in the `fonts/` directory, and the font references in `fonts-override.css`. Then, just import the new `katex.min.js` and `katex.min.css` from the latest version.

If you submit a PR of that, I'll accept it immediately.

**Comment by kaushik1979** [comment]
Got it ... Have made the changes. Testing it right now. Will commit in a day or so. Thanks.

**Comment by kaushik1979** [comment]
Did you get a chance to look at the pull request?

**Comment by kaushik1979** [comment]
I used version - 0.4.2 of katex.

I pulled the latest master and then tried the following equation in the example project. It still doesn't work.

 x = {-b \pm \sqrt{b^2-4ac} \over 2a}

**Comment by stubailo** [comment]
OK I finally published version `1.1.0` of this package, and updated the symlink stuff for the example app so it should work. I have put in your example as the default in the example app.

https://atmospherejs.com/simple/katex

**Comment by kaushik1979** [comment]
Awesome!! Thanks a lot for your help Sashko.

Just updated my project and tested with the following. works like a charm.

f(x) = \int_{-\infty}^\infty \hat f(\xi)\,e^{2 \pi i \xi x} \,d\xi

**Comment by stubailo** [comment]
Yeah, sorry I took so long.
