### ISSUE TITLE
Inline Equations?

### ISSUE THREAD

**Issue by wtruong02151** [stubailo/meteor-katex#5]
Does this package of KaTex include the functionality of inline equations? For example:

    {{katex}}
        This should be normal text, but $3 * \dfrac{40}{50}$ should be displayed as a math formula.
    {{/katex}}

**Comment by stubailo** [comment]
@wtruong02151 I don't know - if KaTeX supports it, then this package should. I'm working on republishing the newest version today thanks to @kaushik1979's pull request, so we'll be on the newest KaTeX soon.

**Comment by kaushik1979** [comment]
@wtruong02151 As far as I know about the use of $ and $$, these are custom tags to find the actual TeX expressions in regular text used in MathJax. I have seen the use of ( and ), \begin and \end, \begin-text and \end-tex.

I myself have implemented the same using begin and end. So a tex expression in my editor will look like  - begin3 \* \dfrac{40}{50}end

I do not think this is a TeX feature that KaTeX will provide.

**Comment by Joe312341** [comment]
Is it currently possible to take a paragraph and change only the math in it to katex?
It looks like katex does this using auto-render...but not sure how I would do it with this package.
Everything I write into the template will be processed as katex.

Example with package: This will not work

```
{{#katex}}
Only the formula is should display in Katex:  \(2+3=5\) 
{{/katex}}
```

Example without using a meteor package: This works

```
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/katex.min.css">
        <script src="http://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/katex.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/contrib/auto-render.min.js"></script>
      </head>
      <body>    
        Only the formula is should display in Katex:  \(2+3=5\) 
        <script>renderMathInElement(document.body)</script>
      </body>
    </html>
```

Thanks
Joe

**Comment by kaushik1979** [comment]
Depends on your regular expressions :)

I do this everywhere in my application. Depending on what delimiters you chose, you can parse the text and then replace the tex part with the following - 
`
'<span class="tex">'+tex_val+'</span>'
`
So your text will become the following - 
`
Only the formula is should display in Katex: <span class="tex">2+3=5</span>
`
This will be rendered as a katex expression in html. I think you should also use {{{ instead of {{ to render the text.

**Comment by stubailo** [comment]
The helper is more of a convenience thing; if you want to do more fancy stuff you can use the katex library directly, as I assume @kaushik1979 is doing.

**Comment by Joe312341** [comment]
Alright thanks for letting me know,

I loaded katex externally and its working out great.

Cheers,
Joe
